---
title: "Car Prices"
subtitle: "Linear Regression"
date: "Week 8"
---


```{r load, include=FALSE}
library(mosaic)
library(pander)
library(tidyverse)
library(DT) 
library(knitr)

# Be sure to download the CarPrices.csv file and save it
# into your Data folder prior to knitting this file.
CarPrices <- read.csv("https://github.com/kctolli/MATH325/raw/master/Data/CarPrices.csv", header=TRUE)

# Remember, to get the CarPrices data into your Console you have
# to use the "Import Dataset" option in the "Environment" window.

```

```{r eval=FALSE}
view(CarPrices)
```

<br>

## Background

Delete these words and write your own background here.  



## Data Analysis {.tabset .tabset-fade}

### Basic Statistics

```{r message=FALSE, warning=FALSE}

```


```{r message=FALSE, warning=FALSE}

```

### Linear Regression

```{r message=FALSE, warning=FALSE}
regress <- function(dat, x1, x2, y){

mylm <- lm(y ~ x1 + x2 + x1:x2, data = dat)
panderlm <- pander(summary(mylm))
panderlm

par(mfrow = c(1,3))
plot(mylm, which = 1:2)
plot(mylm$residuals)

ggplot(dat, aes(x = x, y = y, color = factor(x2))) +
  geom_point() +
  geom_smooth(method = "lm", se=FALSE) +
  theme_bw()
}
```

```{r message=FALSE, warning=FALSE}

```

### The Data

```{r, out.width=300}
pander(phone, split.tables = Inf)
```